### PR TITLE
Support a BIRD2 combined configuration file format

### PR DESCRIPTION
**Pull request by jof**
BIRD 2.x+ supports a combined configuration file format. Support this new calling convention rather than the split v4 and v6 config of BIRD 1.x

### CODE REVIEW

**Comment by pierky** [comment]
@jof thanks a lot for all these PRs. I had to resolve some conflicts, would you mind verifying that I haven't messed up your work? Thanks again!

**Comment by jof** [comment]
@pierky yes, gladly. I will have a look today.

I was making stacked commits and trying to rebase each change onto the master branch so you could pick and choose what to apply, but since the changes were based on each other, I am not surprised that there were a few conflicts. 

I will have a diff today and see if there's anything that needs to be sorted out.

**Comment by jof** [comment]
@pierky -- I diffed my changes, and your conflict resolutions all look correct to me. 🎉 

I'm happily using this to build bird2 and openbgpd configs, generate some HTML, and RPSL as-set objects.

**Comment by pierky** [comment]
Great @jof ! May I ask you for which IX you do it? Is there any reference/doc on the web?

**Comment by jof** [comment]
This is for [SFMIX](https://sfmix.org/) as part of a large automation overhaul this month.

In the near future, I will open source a repo using this at https://github.com/sfmix/sfmix

Once this is in a good place, I also intend to overhaul the website a bit and reference the various open source tools we use, including arouteserver. Do you have any preferred branding or links we should use?
Both [the repo](https://github.com/pierky/arouteserver) and [the readthedocs](https://arouteserver.readthedocs.io/en/latest/) seem like good link targets.

**Comment by pierky** [comment]
> This is for [SFMIX](https://sfmix.org/) as part of a large automation overhaul this month.
> 
> In the near future, I will open source a repo using this at https://github.com/sfmix/sfmix

Great!

> Once this is in a good place, I also intend to overhaul the website a bit and reference the various open source tools we use, including arouteserver. Do you have any preferred branding or links we should use? 

Oh thanks! Just a mention to ARouteServer with a link to the repo would be great.

**Comment by jof** [comment]
https://sfmix.org/route-servers/

**Comment by pierky** [comment]
> https://sfmix.org/route-servers/

Thanks, I've just updated the user list :)

**Pull request merged**
